tasks:
  - init: |
      docker-compose pull
  - command: |
      docker-compose up
ports:
  - port: 3000
    onOpen: ignore
  - port: 8080
    onOpen: open-browser
  - port: 35729
    onOpen: ignore
  - port: 27017
    onOpen: ignore

vscode:
  extensions:
    - ms-azuretools.vscode-docker