version: "3"
services:
  app:
    image: zalook
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      # - MONGODB_USERNAME
      # - MONGODB_PASSWORD
      # - MONGODB_DATABASE
      - MONGODB_CONNECTION_STRING=mongodb://mongo/zalook
    ports:
      - 3000:3000
      - 35729:35729
    volumes:
      - ./src:/app/src
  mongo:
    image: mongo
    ports:
      - 27017:27017
